import { EventItem } from './types';

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'feb-electronics-game',
    title: 'Electronics Game',
    month: 'February 2026',
    week: '2ND WEEK',
    description: 'An interactive electronics-based game designed to strengthen core concepts while encouraging teamwork, logical thinking, and friendly competition among members.Fun + Technical',
    details: 'An interactive electronics-based game designed to strengthen core concepts while encouraging teamwork, logical thinking, and friendly competition among members.',
    category: 'Technical',
    tags: ['Electronics', 'Interactive', 'Challenge'],
    registrationStatus: 'open',
    registeredCount: 42,
    maxCapacity: 120,
    location: 'Main Lab 404',
    time: '2:00 PM - 3:00 PM',
    speaker: 'DCDC Gaming Leads'
  },
  {
    id: 'feb-proj-discussion-2',
    title: 'Project Discussion (Part 2)',
    month: 'February 2026',
    week: '3RD WEEK',
    description: 'Second session of the project discussion and soft-skill series led by senior members, focusing on problem-solving, professional etiquette, and confidence building.',
    details: 'Second session of the project discussion and soft-skill series led by senior members, focusing on problem-solving, professional etiquette, and confidence building.',
    category: 'Projects',
    tags: ['Projects', 'System Architecture', 'Design Review'],
    registrationStatus: 'closed',
    registeredCount: 38,
    maxCapacity: 40,
    location: 'Annex Boardroom C',
    time: '10:00 AM - 1:00 PM',
    speaker: 'Technical Committee Panel'
  },
  {
    id: 'feb-school-outreach',
    title: 'School Outreach Program',
    month: 'February 2026',
    week: '4TH WEEK',
    description: 'Inspiring young minds through robotics and technology by bridging the gap between classroom learning and real-world innovation, empowering the next generation of innovators.',
    details: 'Inspiring young minds through robotics and technology by bridging the gap between classroom learning and real-world innovation, empowering the next generation of innovators.Outreach',
    category: 'Outreach',
    tags: ['Outreach', 'CSR', 'Robotics Education'],
    registrationStatus: 'soon',
    registeredCount: 15,
    maxCapacity: 30,
    location: 'Regional High Schools',
    time: '9:00 AM - 3:00 PM',
    speaker: 'Community Outreach Leads'
  },
  {
    id: 'mar-pcb-design',
    title: 'PCB Design Workshop',
    month: 'March 2026',
    week: '2ND WEEK',
    description: 'Hands-on session on PCB design fundamentals, including schematic creation, layout design, understanding fabrication concepts, and working with PCB software tools.',
    details: 'Hands-on session on PCB design fundamentals, including schematic creation, layout design, understanding fabrication concepts, and working with PCB software tools.',
    category: 'Technical Workshop',
    tags: ['Technical Workshop', 'ECAD', 'Manufacturing'],
    registrationStatus: 'soon',
    registeredCount: 0,
    maxCapacity: 50,
    location: 'Embedded Systems Lab',
    time: '1:00 PM - 5:00 PM',
    speaker: 'Dr. Marcus Holloway (Embedded Architect)'
  },
  {
    id: 'mar-idea-forge',
    title: 'Idea Forge 2026',
    month: 'March 2026',
    week: '3RD WEEK',
    description: 'A platform for students to present innovative ideas. Shortlisted concepts will be taken forward as projects, competitions, or future DCDC initiatives, encouraging creativity and problem-solving.',
    details: 'A platform for students to present innovative ideas. Shortlisted concepts will be taken forward as projects, competitions, or future DCDC initiatives, encouraging creativity and problem-solving. ',
    category: 'Innovation',
    tags: ['Innovation', 'Pitch Deck', 'Product Design'],
    registrationStatus: 'soon',
    registeredCount: 0,
    maxCapacity: 40,
    location: 'The Innovation Incubator Hall',
    time: '10:00 AM - 4:30 PM',
    speaker: 'DCDC Incubation Committee & Guest VC Panels'
  },
  {
    id: 'mar-proj-discussion-3',
    title: 'Project Discussion (Part 3)',
    month: 'March 2026',
    week: '4TH WEEK',
    description: 'Continuation and conclusion of the final mid-semester project evaluation with focused mentoring on execution quality and documentation improvements.',
    details: 'Continuation and conclusion of the final mid-semester project evaluation with focused mentoring on execution quality and documentation improvements.',
    category: 'Projects',
    tags: ['Projects', 'Review Deck', 'Defense Prep'],
    registrationStatus: 'soon',
    registeredCount: 0,
    maxCapacity: 40,
    location: 'Boardroom Annex A',
    time: '3:00 PM - 5:30 PM',
    speaker: 'Senior Evaluation Panel & Tech Leads'
  },
  {
    id: 'apr-fun-event',
    title: 'Fun Event',
    month: 'April 2026',
    week: '1ST WEEK',
    description: 'A non-technical, engaging event featuring games, quizzes, and creative activities to strengthen team bonding and conclude the semester on a fun note.',
    details: 'A non-technical, engaging event featuring games, quizzes, and creative activities to strengthen team bonding and conclude the semester on a fun note.',
    category: 'Club Bonding',
    tags: ['Club Bonding', 'Community', 'Fun'],
    registrationStatus: 'soon',
    registeredCount: 0,
    maxCapacity: 80,
    location: 'DCDC Student Lounge',
    time: '4:00 PM - 6:30 PM',
    speaker: 'DCDC Bonding Coordinators'
  },
  {
    id: 'apr-showcase-day',
    title: 'Project Showcase Day',
    month: 'April 2026',
    week: '2ND WEEK',
    description: 'Final demonstration of all completed projects before a review panel. Projects are evaluated on innovation, execution, and documentation, with recognition for top-performing teams.',
    details: 'Final demonstration of all completed projects before a review panel. Projects are evaluated on innovation, execution, and documentation, with recognition for top-performing teams.',
    category: 'Projects',
    tags: ['Projects', 'Exhibition', 'Awards'],
    registrationStatus: 'soon',
    registeredCount: 0,
    maxCapacity: 60,
    location: 'MIT Block V Exhibition Arena',
    time: '9:30 AM - 4:30 PM',
    speaker: 'DCDC Evaluation Panel'
  },
  {
    id: 'apr-raspberry-pi',
    title: 'Workshop on Raspberry Pi',
    month: 'April 2026',
    week: '3RD WEEK',
    description: 'Beginner-friendly Raspberry Pi workshop covering basic setup, Python programming, and small project demonstrations to help students get started with IoT and embedded systems.',
    details: 'Beginner-friendly Raspberry Pi workshop covering basic setup, Python programming, and small project demonstrations to help students get started with IoT and embedded systems.',
    category: 'Technical Workshop',
    tags: ['Technical Workshop', 'IoT', 'Embedded Systems'],
    registrationStatus: 'soon',
    registeredCount: 0,
    maxCapacity: 50,
    location: 'IoT & Robotics Lab',
    time: '2:00 PM - 5:30 PM',
    speaker: 'DCDC Technical Core Team'
  }
];
